# fly.toml app configuration file generated for programmerbar-status on 2023-09-12T00:20:41+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "programmerbar-status"
primary_region = "arn"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  max_machines_running = 1
  processes = ["app"]
